name: ml4sts
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - scipy=1.5
    - numpy=1.18.1
    - pandas=1.0.5
    - scikit-learn=0.23.1
    - matplotlib=3.2.1
    - isort=4.3.21
    - black=21.5b2
    - identify=2.2.11
    - seaborn=0.10.1
    - setuptools=46.4.0
    - toml=0.10.1
    - tableone=0.7.6
    - tqdm=4.61.2
    - imbalanced-learn=0.7.0
    - pre_commit
    - xgboost=1.0.2
