[tool.black]
line-length = 88

[tool.isort]
length_sort = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
import_heading_stdlib = "Imports: standard library"
import_heading_thirdparty = "Imports: third party"
import_heading_firstparty = "Imports: ml4sts"
default_section = "THIRDPARTY"
known_first_party = "ml4sts"
known_third_party = ["h5py", "matplotlib", "numpy", "pandas", "pytest"]
